/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/try_2.glb --transform 
Files: public/try_2.glb [1.8MB] > D:\Front End\Ahmed-Website\try_2-transformed.glb [143.8KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/try_2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Circle011.geometry} material={materials.PaletteMaterial001} position={[-0.002, 0.366, -0.01]} rotation={[0, -0.187, 0]} scale={0.038} />
      <mesh castShadow geometry={nodes.Circle013.geometry} material={materials.PaletteMaterial002} position={[-0.001, 0.373, -0.009]} rotation={[0, -0.198, 0]} scale={0.031} />
      <mesh castShadow geometry={nodes.Circle014.geometry} material={nodes.Circle014.material} position={[-0.001, 0.373, -0.009]} rotation={[0, -0.198, 0]} scale={0.031} />
      <mesh castShadow geometry={nodes.Sphere002.geometry} material={materials.PaletteMaterial003} position={[-0.002, 0.401, -0.01]} rotation={[0, -0.187, 0]} scale={0.044} />
    </group>
  )
}

useGLTF.preload('/try_2-transformed.glb')
